### ISSUE TITLE
Missing database table error in system log

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-app-matomo#15]
```
Jun 02 19:06:03 ubosbox php[12318]: ERROR [2020-06-02 19:06:03] 12318  Uncaught exception: /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/libs/Zend/Db/Statement/Mysqli.php(77): Mysqli prepare error: Table 'pdlsrzzsmyyjejnx.matomo_segment' doesn't exist
Jun 02 19:06:03 ubosbox php[12318]: Mysqli prepare error: Table 'pdlsrzzsmyyjejnx.matomo_segment' doesn't exist
Jun 02 19:06:03 ubosbox php[12318]: #0 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/libs/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare()
Jun 02 19:06:03 ubosbox php[12318]: #1 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/libs/Zend/Db/Adapter/Mysqli.php(419): Zend_Db_Statement->__construct()
Jun 02 19:06:03 ubosbox php[12318]: #2 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/libs/Zend/Db/Adapter/Abstract.php(478): Zend_Db_Adapter_Mysqli->prepare()
Jun 02 19:06:03 ubosbox php[12318]: #3 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/libs/Zend/Db/Adapter/Abstract.php(736): Zend_Db_Adapter_Abstract->query()
Jun 02 19:06:03 ubosbox php[12318]: #4 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/plugins/SegmentEditor/Model.php(38): Zend_Db_Adapter_Abstract->fetchAll()
Jun 02 19:06:03 ubosbox php[12318]: #5 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/core/CronArchive.php(616): Piwik\Plugins\SegmentEditor\Model->getAllSegmentsAndIgnoreVisibility()
Jun 02 19:06:03 ubosbox php[12318]: #6 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/plugins/CoreConsole/Commands/CoreArchiver.php(60): Piwik\CronArchive->setSegmentsToForceFromSegmentIds()
Jun 02 19:06:03 ubosbox php[12318]: #7 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/plugins/CoreConsole/Commands/CoreArchiver.php(26): Piwik\Plugins\CoreConsole\Commands\CoreArchiver::makeArchiver()
Jun 02 19:06:03 ubosbox php[12318]: #8 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute()
Jun 02 19:06:03 ubosbox php[12318]: #9 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
Jun 02 19:06:03 ubosbox php[12318]: #10 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
Jun 02 19:06:03 ubosbox php[12318]: #11 [internal function]: Symfony\Component\Console\Application->doRun()
Jun 02 19:06:03 ubosbox php[12318]: #12 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/core/Console.php(140): call_user_func()
Jun 02 19:06:03 ubosbox php[12318]: #13 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/core/Access.php(644): Piwik\Console->Piwik\{closure}()
Jun 02 19:06:03 ubosbox php[12318]: #14 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/core/Console.php(141): Piwik\Access::doAsSuperUser()
Jun 02 19:06:03 ubosbox php[12318]: #15 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/core/Console.php(93): Piwik\Console->doRunImpl()
Jun 02 19:06:03 ubosbox php[12318]: #16 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
Jun 02 19:06:03 ubosbox php[12318]: #17 /ubos/http/sites/s3c59025e8c583a87e15629a3b8ebd7bb8c1a3ade/console(32): Symfony\Component\Console\Application->run()
Jun 02 19:06:03 ubosbox php[12318]: #18 {main}
Jun 02 19:06:03 ubosbox php[12318]:                                                                                
Jun 02 19:06:03 ubosbox php[12318]:   [Zend_Db_Statement_Mysqli_Exception]
Jun 02 19:06:03 ubosbox php[12318]:   Mysqli prepare error: Table 'pdlsrzzsmyyjejnx.matomo_segment' doesn't exist
Jun 02 19:06:03 ubosbox php[12318]:                                                                                
Jun 02 19:06:03 ubosbox php[12318]: core:archive [--url="..."] [--force-all-websites] [--force-all-periods[="..."]] [--force-timeout-for-periods[="..."]] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--skip-segments-today] [--force-periods[="..."]] [--force-date-last-n="..."] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]]
Jun 02 19:06:03 ubosbox systemd[1]: matomo-archive@a887ff2f9b2b870409def0b7cd328a4e339f1ade3.service: Main process exited, code=exited, status=255/EXCEPTION
```

That's apparently when the archive timer/service runs before the database has been populated.

**Comment by jernst** [comment]
This still happens upon upgrade. Maybe the delay is ignored because the unit wasn't freshly installed? Stackoverflow suggests adding a sleep statement in the `Pre` script.

**Comment by jernst** [comment]
Trying to remove the `OnBootSec`, maybe that is better?
